name: Backend CD Pipeline

on:
  workflow_run:
    workflows: ["Backend CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: SSH into EC2 and update Docker container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: | 
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rm-backend:${{ github.sha }}
          docker stop rm-backend || true 
          docker rm rm-backend || true 
          docker run -d --name rm-backend \
          -e DB_URL=${{ secrets.DB_URL }} \
          -e EMAIL_NAME=${{ secrets.EMAIL_NAME }} \
          -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
          -e PORTONE_CODE=${{ secrets.PORTONE_CODE }} \
          -e PORTONE_KEY=${{ secrets.PORTONE_KEY }} \
          -e PORTONE_SECRET_KEY=${{ secrets.PORTONE_SECRET_KEY }} \
          -e JWT_ACCESS=${{ secrets.JWT_ACCESS }} \
          -e JWT_REFRESH=${{ secrets.JWT_REFRESH }} \
          -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
          -e S3_KEY=${{ secrets.S3_KEY }} \
          -e S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/rm-backend:${{ github.sha }}
