name: Front User CD Pipeline

on:
  workflow_run:
    workflows: ["Front User CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: SSH into EC2 and update Docker container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: | 
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rm-front-user:${{ github.sha }}
          docker stop rm-front-user || true 
          docker rm rm-front-user || true 
          docker run -d --name rm-front-user \
          --network real-moment-network \
          -e BACKEND_HOST=${{ secrets.BACKEND_HOST }} \
          -e PORTONE_CODE=${{ secrets.PORTONE_CODE }} \
          -p 80:80 \
          ${{ secrets.DOCKERHUB_USERNAME }}/rm-front-user:${{ github.sha }}
