name: Front Admin CD Pipeline

on:
  workflow_run:
    workflows: ["Front Admin CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: SSH into EC2 and update Docker container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: | 
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rm-front-admin:latest 
          docker stop rm-front-admin || true 
          docker rm rm-front-admin || true 
          docker run -d --name rm-front-admin -e ${{ secrets.BACKEND_HOST }} -p 81:80 ${{ secrets.DOCKERHUB_USERNAME }}/rm-front-admin:latest
