name: Front Admin CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'rm-front-admin/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./rm-front-admin
        file: ./rm-front-admin/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rm-front-admin:${{ github.sha }}
        platforms: linux/amd64,linux/arm64